### ISSUE TITLE
phpBB encountered an error building (more in topic)

### ISSUE THREAD

**Issue by Scorpions95** [tierra/topicsolved#82]
im getting this error when enable this extension 

```
phpBB encountered an error building the container due to an installed extension. For this reason, all extensions have been temporarily disabled. Please try purging your forum cache. All extensions will automatically be re-enabled once the container error is resolved. If this error continues, please visit phpBB.com for support.


Exception: The file "/home/bgrockeu/public_html/ext/tierra/topicsolved/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 5 (near "- @tierra.topicsolved.topicsolved").

#0 /home/bgrockeu/public_html/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/bgrockeu/...')
#1 /home/bgrockeu/public_html/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /home/bgrockeu/public_html/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /home/bgrockeu/public_html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /home/bgrockeu/public_html/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /home/bgrockeu/public_html/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /home/bgrockeu/public_html/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /home/bgrockeu/public_html/phpbb/di/container_builder.php(223): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /home/bgrockeu/public_html/common.php(117): phpbb\di\container_builder->get_container()
#9 /home/bgrockeu/public_html/adm/index.php(23): require('/home/bgrockeu/...')
#10 {main}
```
also tried to install topicsolved-2.3.0 version, but still get same error

**Comment by FlitPix** [comment]
A fix is documented [here](https://www.phpbb.com/customise/db/extension/topic_solved/support/topic/241026?p=868315#p868315) that works for me on phpBB 3.3.13 and topicsolved 2.2.0.

**Comment by FlitPix** [comment]
It seems this was fixed in 531c116746e05b4636b9cba1a4da78ec68ef57b8 but a release was never made.
